title: Jinpei Ling # your name (or website title) here
logo: "/images/images.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>Senior Web and Mobile Developer<br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/jinpei-ling-09630a18a">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
