title: Cristian Silva # your name (or website title) here
logo: "/images/images.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h3>Sr. Web && Mobile Engineer</h3>
  I'm a senior web developer having 8 years of experience, especially with React.js and React Native for over 4 years since it was released by Facebook. I love programming web and mobile applications using React.js and React Native.
  <br>
  I can work full time (more than 40 hours a week) in PST time and contribute great and fast working. Please don't hesitate to hire me here. Looking forward to learning a bit more from you.
  <br>
  Regards
  <br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
