title: Jinpei Ling # your name (or website title) here
logo: "/images/images.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm a senior web developer having 8 years of experience, especially with React.js and React Native for over 4 years since it was released by Facebook. I love programming web and mobile applications using React.js and React Native. | Nowadays, React.js is a very famous and reliable Javascript library and it has almost completed.> In additions, I'm familiar with many Javascript libraries and backend frameworks.
  <br><br>
  My skills include; | - React.js, React Native, Redux | - AngularJS, Vue.js, Node.js, Express.js, Chart.js, Puppet.js, and etc | - Python, Django, Laravel as backend frameworks | - PostgreSQL, MySQL, MongoDB as database | - Third party apis such as Google Map API, Google Authentication
  <br></br>
  I can work full time (more than 40 hours a week) in PST time and contribute great and fast working. | Please don't hesitate to hire me here. | Looking forward to learning a bit more from you.
  <br></br>
  Regards
  <br><br>
  <a href="https://www.linkedin.com/in/jinpei-ling-09630a18a">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
